<?php

namespace Database\Seeders;

use App\Models\RW;
use App\Models\RT;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class RtSeeder extends Seeder
{

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rts = [
            [
                'rw_id' => 1,
                'name' => 'RT 001',
                'leader_name' => "TATA",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 1,
                'name' => 'RT 002',
                'leader_name' => "ILIN SOLIHIN",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 1,
                'name' => 'RT 003',
                'leader_name' => "JAJANG S.ROHMAN",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 1,
                'name' => 'RT 004',
                'leader_name' => "SOMA HIDAYAT",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 2,
                'name' => 'RT 001',
                'leader_name' => "NENG SRI WAHYUNI",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 2,
                'name' => 'RT 002',
                'leader_name' => "NASIHIN ALAWI",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 2,
                'name' => 'RT 003',
                'leader_name' => "MAMAN",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 3,
                'name' => 'RT 001',
                'leader_name' => "UBED SUDRAJAT",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 3,
                'name' => 'RT 002',
                'leader_name' => "YUYUN",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 4,
                'name' => 'RT 001',
                'leader_name' => "SITI KHOLIFAH",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 4,
                'name' => 'RT 002',
                'leader_name' => "DEDE ISNANDAR",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 4,
                'name' => 'RT 003',
                'leader_name' => "HADI",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 5,
                'name' => 'RT 001',
                'leader_name' => "CAHYA",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 5,
                'name' => 'RT 002',
                'leader_name' => "ENAH",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 6,
                'name' => 'RT 001',
                'leader_name' => "TONO S.",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 6,
                'name' => 'RT 002',
                'leader_name' => "SOBARI",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 6,
                'name' => 'RT 003',
                'leader_name' => "IMAN",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 7,
                'name' => 'RT 001',
                'leader_name' => "ADE H.",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 7,
                'name' => 'RT 002',
                'leader_name' => "ANANG",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 8,
                'name' => 'RT 001',
                'leader_name' => "OMAN",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 8,
                'name' => 'RT 002',
                'leader_name' => "JENAL",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 8,
                'name' => 'RT 003',
                'leader_name' => "YAYU ABDULLAH",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 9,
                'name' => 'RT 001',
                'leader_name' => "MIFTAH",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 9,
                'name' => 'RT 002',
                'leader_name' => "ADE SADIAH",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 9,
                'name' => 'RT 003',
                'leader_name' => "H. SARNADI",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 9,
                'name' => 'RT 004',
                'leader_name' => "ADE IJUDIN",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 10,
                'name' => 'RT 001',
                'leader_name' => "JAENUDIN",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 10,
                'name' => 'RT 002',
                'leader_name' => "FITRI",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 10,
                'name' => 'RT 003',
                'leader_name' => "JUANDA",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 11,
                'name' => 'RT 001',
                'leader_name' => "DUDUNG SUTISNA",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 11,
                'name' => 'RT 002',
                'leader_name' => "AGUS",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 12,
                'name' => 'RT 001',
                'leader_name' => "RACHMAT SUDRAJAT",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 12,
                'name' => 'RT 002',
                'leader_name' => "JEJENG",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 13,
                'name' => 'RT 001',
                'leader_name' => "AGUS",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'rw_id' => 13,
                'name' => 'RT 002',
                'leader_name' => "USIN",
                'phone' => "",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
        RT::insert($rts);
    }
}